from __future__ import annotations

import threading
import time
from typing import Dict, Any, Optional, List

from visualization.charts.radar import RadarChart
from visualization.charts.bar import BarChart
from visualization.charts.pie import PieChart
from visualization.charts.time_series import TimeSeriesChart


class GovernanceDashboard:
    """
    Institutional Governance Dashboard

    Responsibilities
    ----------------
    • Visualize trader governance tier
    • Visualize risk control and survival state
    • Visualize governance category scores

    IMPORTANT
    ---------
    This dashboard NEVER computes governance metrics.

    It ONLY visualizes outputs generated by:

        decisions/governance_levels.py
        decisions/decision_engine.py
        survival/survival_engine.py
        risk_control/ modules
    """

    VERSION = 1

    def __init__(self, monitoring_registry: Optional[Any] = None):

        self._monitoring_registry = monitoring_registry

        self._charts: Dict[str, Any] = {}

        self._lock = threading.Lock()

        self._metadata = {
            "created_at": time.time(),
            "version": self.VERSION
        }

    # -------------------------------------------------
    # Trader Tier Profile
    # -------------------------------------------------

    def build_governance_profile(
        self,
        governance_metrics: List[str],
        scores: List[float],
    ) -> None:

        chart = RadarChart(
            "Governance Profile",
            monitoring_registry=self._monitoring_registry,
        )

        chart.set_axes(governance_metrics)

        chart.add_profile(
            "Trader Governance",
            scores
        )

        chart.configure_layout(
            radial_min=0,
            radial_max=100
        )

        with self._lock:
            self._charts["governance_profile"] = chart.export()

    # -------------------------------------------------
    # Governance Category Breakdown
    # -------------------------------------------------

    def build_governance_breakdown(
        self,
        categories: List[str],
        scores: List[float]
    ) -> None:

        chart = BarChart(
            "Governance Category Scores",
            monitoring_registry=self._monitoring_registry
        )

        chart.set_categories(categories)

        chart.add_series(
            "score",
            scores
        )

        chart.configure_layout(
            x_label="Governance Category",
            y_label="Score"
        )

        with self._lock:
            self._charts["governance_breakdown"] = chart.export()

    # -------------------------------------------------
    # Trader Tier Distribution
    # -------------------------------------------------

    def build_tier_distribution(
        self,
        tiers: List[str],
        values: List[int]
    ) -> None:

        chart = PieChart(
            "Trader Tier Distribution",
            monitoring_registry=self._monitoring_registry
        )

        chart.set_slices(
            labels=tiers,
            values=values
        )

        chart.configure_layout(
            show_percentage=True
        )

        with self._lock:
            self._charts["tier_distribution"] = chart.export()

    # -------------------------------------------------
    # Risk Control Status
    # -------------------------------------------------

    def build_risk_control_status(
        self,
        controls: List[str],
        values: List[float]
    ) -> None:

        chart = BarChart(
            "Risk Control Status",
            monitoring_registry=self._monitoring_registry
        )

        chart.set_categories(controls)

        chart.add_series(
            "risk_control_score",
            values
        )

        chart.configure_layout(
            x_label="Risk Control",
            y_label="Score"
        )

        with self._lock:
            self._charts["risk_control_status"] = chart.export()

    # -------------------------------------------------
    # Governance Trend
    # -------------------------------------------------

    def build_governance_trend(
        self,
        timestamps: List[Any],
        governance_scores: List[float]
    ) -> None:

        chart = TimeSeriesChart(
            "Governance Trend",
            monitoring_registry=self._monitoring_registry
        )

        chart.add_series(
            "governance_score",
            timestamps,
            governance_scores
        )

        chart.configure_axes(
            x_label="Time",
            y_label="Governance Score"
        )

        with self._lock:
            self._charts["governance_trend"] = chart.export()

    # -------------------------------------------------
    # Export
    # -------------------------------------------------

    def export(self) -> Dict[str, Any]:

        with self._lock:

            return {
                "dashboard_type": "governance",
                "charts": dict(self._charts),
                "metadata": dict(self._metadata)
            }

    # -------------------------------------------------
    # Snapshot
    # -------------------------------------------------

    def snapshot(self) -> Dict[str, Any]:

        with self._lock:

            return {
                "dashboard_type": "governance",
                "chart_count": len(self._charts),
                "timestamp": time.time()
            }